### ISSUE TITLE
build errror

### ISSUE THREAD

**Issue by halkoy** [merbin2012/cordova-plugin-codeplay-facebookads-free#1]
What went wrong:
A problem occurred evaluating script.
> Could not find method implementation() for arguments [com.android.support:recyclerview-v7:25.3.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler

**Comment by merbin2012** [comment]
@halkoy can you give me a screenshot.

**Comment by halkoy** [comment]
@merbin2012 
![image](https://user-images.githubusercontent.com/22586788/59147003-35dec080-89fe-11e9-900b-5d1f91712967.png)

**Comment by halkoy** [comment]
FAILURE: Build failed with an exception.

* Where:
Script '/var/gimlet/tmp/47124399311280/2633291/project/cordova-plugin-codeplay-facebookads-free/behonest-facebook-sdk.gradle' line: 2

* What went wrong:
A problem occurred evaluating script.
> Could not find method implementation() for arguments [com.android.support:recyclerview-v7:25.3.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/var/gimlet/tmp/47124399311280/2633291/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by merbin2012** [comment]
Which version of Android studio you using?

**Comment by halkoy** [comment]
@merbin2012 
I am using online phonegap build . Adobe phonegap build.  https://build.phonegap.com/

I dont use android studio

**Comment by merbin2012** [comment]
Ooh, sorry dear might they using low version of android studio. That is why it show this error. implementation method is new, please refer the following link
https://stackoverflow.com/questions/44493378/whats-the-difference-between-implementation-and-compile-in-gradle

I'm strongly recommend you to avoid online build. If you have any problem for making your own application download and learn from my Android Code Play app
https://play.google.com/store/apps/details?id=cordova.code.play
Thanks for your comments, and now I'm closing this bug due to old version of android studio. If you feel I'm mistaken feel free to open it again.

**Comment by halkoy** [comment]
which phonegap, cordova version are you using?
cli-8.1.1 ?

**Comment by merbin2012** [comment]
@halkoy I think it depends on an SDK version.
